{
    "name": "Build",
    "on": { "pull_request": null },
    "jobs": {
        "linux": {
            "runs-on": "ubuntu-latest",
            "strategy": {
                "fail-fast": false,
                "matrix": {
                    "python": [
                        "3.6",
                        "3.7",
                        "3.8",
                        "3.9",
                    ],
                },
            },
            "steps": [
                { "uses": "actions/checkout@v2" },
                {
                    "uses": "actions/setup-python@v2",
                    "with": { "python-version": "${{ matrix.python }}"},
                },
                { "run": "sudo apt update" },
                { "run": "sudo apt install -y libkrb5-dev" },
                { "run": "pip install flake8" },
                { "run": "pip install -r requirements.txt" },
                { "run": "python3 -m unittest" },
                {
                    "run": "flake8",
                    "if": "${{ matrix['python'] == 3.9 }}",
                },
            ],
        },
    },
}
